version: "3"

services:
  backend:
    env_file: "./server/.env"
    build:
      context: ./server
      dockerfile: ./Dockerfile
    image: "ht-perfanalytics/server"
    ports:
      - "6060:6060"
  frontend:
    build:
      context: ./client
      dockerfile: ./Dockerfile
    image: "ht-perfanalytics/client"
    ports:
      - "80:3000"
