name: Deploy API to Heroku

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Create local changes & push to GitHub
        run: cd PerfAnalytics.API && yarn install && yarn build

      - name: Add remote origin
        run: git remote add heroku https://heroku:70d4eaa8-2db9-465d-a31d-aa3eadd54c5d@git.heroku.com/ht-perfanalytics-api.git

      - name: Deploy backend to heroku
        run: git push --force heroku `git subtree split --prefix PerfAnalytics.API HEAD`:master
