name: "Deploy APP to Heroku"

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build, Push and Deploy to Heroku
        id: heroku
        uses: snithyanantham/docker-compose-multiple-apps-heroku-deploy@v1.0
        with:
          email: "hasantezcan77+dummy@gmail.com"
          api_key: "0b4dc590-65f8-4ddc-91a1-4766190ee4fa"
          docker_compose_file: "./docker-compose.yml"
          heroku_apps: '[{"imagename":"ht-perfanalytics/client","appname":"ht-perfanalytics/client","apptype":"web"},{"imagename":"ht-perfanalytics/server","appname":"ht-perfanalytics/server","apptype":"worker"}]'
